---
title: "SocKult analysis"
author: "Annamaya Halskov-Jensen"
date: "14/5/2019"
output: pdf_document
---

LOADING AND PREPARATION
```{r}

setwd("/Users/annamayahalskov-jensen/Documents/Cognitive Science/4th semester/Social and cultural dynamics in cognition/SocKult Exam")
library(pacman)
p_load("coda", "mvtnorm", "devtools", "rstan", "rethinking", "tidyverse", "dfcrm", "brms")

data <- read.csv("full_set.csv")
data_test <- data %>% select(ID, condition, steps)

data_test$condition <- as.character(data_test$condition)
data_test$condition[data_test$condition == "cooperative"] <- "0"
data_test$condition[data_test$condition == "competitive"] <- "1"
data_test$condition <- as.factor(data_test$condition)

#Standardize predictors to a mean of 0 and sd of 1
data_test$steps.s = (data_test$steps - mean(data_test$steps, na.rm = T))/ sd(data_test$steps)

```


CONDITION ONLY
```{r vIQ + ados} 
 
# defining model first
m0 <-  bf(steps ~ 1 + condition)
dens (v1_asd$VerbalIQ)
dens (v1_asd$ADOS)
 
# Getting the priors
get_prior(steps ~ 1 + condition, data, family = gaussian)

# Defining priors used
prior = c(
  prior(normal(50, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'), 
  prior(normal(0, 10), class = 'sigma'))

# modelling 
m0_prior <- brm(m0, family = gaussian, data, prior = prior, sample_prior = "only")
m0.b <- brm(m0, family = gaussian, data, prior = prior)
m0.b

# If set to "only", samples are drawn solely from the priors ignoring the likelihood, which allows among others to generate samples from the prior predictive distribution. In this case, all parameters must have proper priors.

# Checking priors
pp_check(m0_prior, nsample = 100)

# MAP
flist <-  alist(
    steps ~ dnorm(mu , sigma),
    mu <- a + b * condition,
        a ~ dnorm(50, 10),
        b ~ dnorm(20, 10),
        sigma ~ dunif(0, 10))

m.m0 <- rethinking::map(flist, data = data)
precis(m.m0) 
precis_plot(precis(m.m0))
```


CONDITION + TOM
```{r}
# defining model first
m1 <-  bf(steps ~ 1 + condition + tom)

# Getting the priors
get_prior(steps ~ 1 + condition + tom, data, family = gaussian)

# Defining priors used
prior = c(
  prior(normal(50, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma'))

# modelling in brms
m1.1_prior <- brm(m1, family = gaussian, data, prior = prior, sample_prior = "only")
m1.1.b <- brm(m1, family = gaussian, data, prior = prior)
m1.1.b

# Checking priors
pp_check(m1_prior, nsample = 100)

# MAP
flist <-  alist(
    steps ~ dnorm(mu , sigma),
    mu <- a + bc * condition + bt * tom,
        a ~ dnorm(50, 10),
        bc ~ dnorm(20, 10),
        bt ~ dnorm(10, 10),
        sigma ~ dunif(0, 10))

m.m1 <- rethinking::map(flist, data = data)
```


CONDITION + COMPETENCE
```{r}
# defining model first
m2 <-  bf(steps ~ 1 + condition + competence)

# Getting the priors
get_prior(steps ~ 1 + condition + competence, data, family = gaussian)

# Defining priors used
prior = c(
  prior(normal(50, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma'))

# modelling in brms
m1.2_prior <- brm(m2, family = gaussian, data, prior = prior, sample_prior = "only")
m1.2.b <- brm(m2, family = gaussian, data, prior = prior)
m1.2.b

plot(m2.b)

# Checking priors
pp_check(m2_prior, nsample = 100)

# MAP
flist <-  alist(
    steps ~ dnorm(mu , sigma),
    mu <- a + bc * condition + bcc * competence,
        a ~ dnorm(50, 10),
        bc ~ dnorm(20, 10),
        bcc ~ dnorm(10, 10),
        sigma ~ dunif(0, 10))

m.m2 <- rethinking::map(flist, data = data)
```


WAIC COMPARISON MODEL 0 + 1.1 + 1.2
```{r}
# compute and save the WAIC information for the next three models
m0.b <- add_criterion(m0.b, "waic")
m1.1.b <- add_criterion(m1.1.b, "waic")
m1.2.b <- add_criterion(m1.2.b, "waic")

# compare the WAIC estimates
w <- loo_compare(m0.b, m1.1.b, m1.2.b, criterion = "waic")
print(w, simplify = F)

#Calculating weights
model_weights(m0.b, m1.1.b, m1.2.b, weights = "waic") %>% 
  round(digits = 2)
```


CONDITION * TOM
```{r}
# defining model first
m2.1 <-  bf(steps ~ 1 + condition * tom)

# Getting the priors
get_prior(steps ~ 1 + condition * tom, data, family = gaussian)

# Defining priors used
prior = c(
  prior(normal(50, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma'))

# modelling in brms
m2.1_prior <- brm(m2, family = gaussian, data, prior = prior, sample_prior = "only")
m2.1.b <- brm(m2.1, family = gaussian, data, prior = prior)
m2.1.b

plot(m2.1.b)

# Checking priors
pp_check(m2.1_prior, nsample = 100)

# MAP
flist <-  alist(
    steps ~ dnorm(mu , sigma),
    mu <- a + bc * condition + bcc * competence,
        a ~ dnorm(50, 10),
        bc ~ dnorm(20, 10),
        bcc ~ dnorm(10, 10),
        sigma ~ dunif(0, 10))

m.m2 <- rethinking::map(flist, data = data)
```


WAIC COMPARISON MODEL 1.1 + 2.1
```{r}
# compute and save the WAIC information for the next three models
m2.1.b <- add_criterion(m2.1.b, "waic")

# compare the WAIC estimates
w <- loo_compare(m1.1.b, m2.1.b, criterion = "waic")
print(w, simplify = F)

#Calculating weights
model_weights(m2.1.b, m2.1.b, weights = "waic") %>% 
  round(digits = 2) 
```


CONDITION * TOM + COMPETENCE
```{r}
# defining model first
m3.1 <-  bf(steps ~ 1 + condition * tom + competence)

# Getting the priors
get_prior(steps ~ 1 + condition * tom + competence, data, family = gaussian)

# Defining priors used
prior = c(
  prior(normal(50, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma'))

# modelling in brms
m3.1_prior <- brm(m3.1, family = gaussian, data, prior = prior, sample_prior = "only")
m3.1.b <- brm(m2.1, family = gaussian, data, prior = prior)
m3.1.b

plot(m3.1.b)

# Checking priors
pp_check(m3.1_prior, nsample = 100)
```


CONDITION * TOM * COMPETENCE
```{r}
# defining model first
m3.2 <-  bf(steps ~ 1 + condition * tom * competence)

# Getting the priors
get_prior(steps ~ 1 + condition * tom * competence, data, family = gaussian)

# Defining priors used
prior = c(
  prior(normal(50, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'),
  prior(normal(0, 10), class = 'sigma'))

# modelling in brms
m3.2_prior <- brm(m3.2, family = gaussian, data, prior = prior, sample_prior = "only")
m3.2.b <- brm(m3.2, family = gaussian, data, prior = prior)
m3.2.b

plot(m3.2.b)

# Checking priors
pp_check(m3.1_prior, nsample = 100)
```


WAIC COMPARISON MODEL 2.1 + 3.1
```{r}
# compute and save the WAIC information for the next three models
m3.1.b <- add_criterion(m3.1.b, "waic")
m3.2.b <- add_criterion(m3.2.b, "waic")

# compare the WAIC estimates
w <- loo_compare(m3.1.b, m2.1.b, m3.2.b, criterion = "waic")
print(w, simplify = F)

#Calculating weights
model_weights(m2.1.b, m3.1.b, m3.1.b, weights = "waic") %>% 
  round(digits = 2) 
```


