---
title: 'Assignment 5: Questioning Game Theory'
author: "Annamaya Halskov-Jensen"
date: "18/5/2019"
output: pdf_document
---

LOADING AND PREPARATION
```{r}
setwd("/Users/annamayahalskov-jensen/Documents/Cognitive Science/4th semester/Social and cultural dynamics in cognition/SocKult Exam")
library(pacman)
p_load("coda", "mvtnorm", "devtools", "rstan", "rethinking", "tidyverse", "dfcrm", "brms", "RColorBrewer", "MCMCvis")

data <- read.csv("full_set.csv")
tom <- read.csv("tom_trials - Ark1.csv")
```


INVESTIGATING TOM
```{r}
ggplot(tom, aes(trial, tom)) +
  geom_point(aes(colour=ID)) +
  geom_smooth(aes(colour=ID), se = F)

#method = "gam", formula = y ~ s(x, bs = "cs")

xlab <- "Trial" 
ylab <- "Measure of Theory of Mind"
num <- 2
getPalette <- colorRampPalette(brewer.pal(8, "Accent"))

ggplot(tom, aes(trial, tom)) +
  geom_point(aes(colour = ID), size = 2) +
  scale_color_manual(values = getPalette(num)) +
  geom_line(aes(colour = ID), size = 1) +
  labs(x = xlab, y = ylab) +
  scale_y_continuous(breaks = c(-10:20)) +
  scale_x_continuous(breaks = c(1:3))
```


PLOTTING RAW DATA
```{r}
ggplot(data, aes(steps)) + 
  geom_density(aes(fill = condition, colour = condition), alpha = 0.3) + 
  facet_wrap(~condition)

ggplot(data, aes(steps)) + 
  geom_density(aes(fill = competence, colour = competence), alpha = 0.3) + 
  facet_wrap(~competence)

ggplot(data, aes(tom, steps)) +
  geom_point(aes(colour = condition))

ggplot(data, aes(competence, steps)) +
  geom_point(aes(colour = condition))
```


PRIORS
```{r}
# Defining priors used
prior0 = c(
  prior(normal(20, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'sigma'))

prior_20 = c(
  prior(normal(20, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'), 
  prior(normal(0, 10), class = 'sigma'))

prior_10 = c(
  prior(normal(10, 10), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'), 
  prior(normal(0, 10), class = 'sigma'))

prior_new = c(
  prior(normal(20, 5), class = 'Intercept'), 
  prior(normal(0, 10), class = 'b'), 
  prior(normal(0, 10), class = 'sigma'))
```


PREDICTIVE PRIOR CHECK(S)
```{r}
m0.0_prior <- brm(steps ~ 1, family = gaussian, data, prior = prior0, sample_prior = "only")
m0_prior <- brm(steps ~ 1 + condition, family = gaussian, data, prior = prior_new, sample_prior = "only")
m4.1_prior <- brm(steps ~ 1 + condition + tom + competence, family = gaussian, data, prior = prior_new, sample_prior = "only")
m1.3_prior <- brm(steps ~ 1 + tom + competence, family = gaussian, data, prior = prior_new, sample_prior = "only")
m3.1_prior <- brm(steps ~ 1 + condition * tom + competence, family = gaussian, data, prior = prior_new, sample_prior = "only")

pp_check(m0.0_prior, nsample = 100)
pp_check(m0_prior, nsample = 100)
pp_check(m4.1_prior, nsample = 100)
pp_check(m1.3_prior, nsample = 100)
pp_check(m3.1_prior, nsample = 100)
 
```


0.0: INTERCEPT ONLY
```{r}  
# modelling 
m0.0 <- brm(steps ~ 1, family = gaussian, data, prior = prior0)
m0.0
plot(m0.0)

# Checking posterior
pp_check(m0.0, nsample = 20)
```


0: CONDITION ONLY
```{r}
# modelling 
m0 <- brm(steps ~ 1 + condition, family = gaussian, data, prior = prior_new)
m0
plot(m0)

# Checking posterior
pp_check(m0, nsample = 20)
```


1.3: TOM + COMPETENCE
```{r}
# modelling in brms 
m1.3 <- brm(steps ~ 1 + tom + competence, family = gaussian, data, prior = prior_new)
m1.3 
plot(m1.3) 

# Checking posterior
pp_check(m1.3, nsample = 20)
```


3.1: CONDITION * TOM + COMPETENCE
```{r}
# modelling in brms
m3.1 <- brm(steps ~ 1 + condition * tom + competence, family = gaussian, data, prior = prior_new)
m3.1 
plot(m3.1)

# checking posterior
pp_check(m3.1, nsample = 20)

# marginal effects
marginal <- brms::marginal_effects(m3.1)
plot(marginal, plot = F)[[4]] +
  scale_color_brewer(type = "qual", palette = "Set1") +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  labs(title = "Marginal effects of ToM & condition", x = "ToM", y = "Steps from $100") +
  theme_minimal()
```


4.1: CONDITION + TOM + COMPETENCE
```{r} 
# modelling in brms
m4.1 <- brm(steps ~ 1 + condition + tom + competence, family = gaussian, data, prior = prior_new)
m4.1 
plot(m4.1)

# Checking posterior
p4.1 <- pp_check(m4.1, nsample = 20)

```


WAIC COMPARISON MODEL 0.0, 0, 1.3, 3.1 & 4.1
```{r} 
# adding waic
m0 <- add_criterion(m0, "waic") 
m0.0 <- add_criterion(m0.0, "waic")
m1.3 <- add_criterion(m1.3, "waic")
m3.1 <- add_criterion(m3.1, "waic")
m4.1 <- add_criterion(m4.1, "waic")

# compare the WAIC estimates
waic <- loo_compare(m0.0, m0, m1.3, m3.1, m4.1, criterion = "waic")
print(waic, simplify = F)

#Calculating weights
model_weights(m0.0, m0, m1.3, m3.1, m4.1, weights = "waic") %>% 
  round(digits = 2)
```


PREDICTIONS OF MODEL 1.3
```{r}
# calculating predictions for m1.3
pred3 <- predict(m1.3)
pred3 <- as.data.frame(pred3)
pred3$actual <- data$steps
pred3$tom <- data$tom
pred3$competence <- data$competence

# plotting predictions vs. actual data (density)
p3_steps <- ggplot(pred3, aes(actual)) + 
  geom_density(aes(fill = tom, colour = tom), alpha = 0.3)

p3_pred <- ggplot(pred3, aes(Estimate)) + 
  geom_density(aes(fill = competence, colour = competence), alpha = 0.3)

plots3 <- plot_grid(p3_steps, p3_pred)

# plotting predictions vs. actual data (points)
ggplot(pred3, aes(actual, Estimate)) +
  geom_smooth(color = "#449999", method = "lm", se = F) +
  geom_point(color = "Dark red") +
  geom_abline(xintercept = 100, yintercept = 100, linetype = "dashed") +
  xlim(0, 100) +
  ylim(0, 100) +
  theme_minimal() +
  labs(title = "Observation vs. Prediction - Model 3", x = "Observed values (steps)", y = "Model predictions (steps)")

```
